dist: xenial

language: scala
scala:
  - 3.0.1

addons:
  sonarcloud:
    organization: "pps-authsim"
    token:
      #secure: "jvwtXaE6beFJbZYbI4zFgZr9LNvGd7WNYP6WLomKJgI7TKi+xFFcpNdgIal7jVI5deaoJ6aT1UxpEnwxpYCva/2XojApwGZPjVRGg94Xx88LZh7rigymDUaqtqOr/D58aFGaqksdiHXzB25SPZLtkyfWf7CuMptvKTMxeb8kMG0GvKYPbAmbaFxaRjh9CLo5d4Tm53myDpfn/S+irX9Vwtm5GBq9D8BMK1GQHtn0irqUoVXs9ID19WBa2K+f0P03405wgcmsAqJzCXDnVM+Ct/Woht5aTktaYiNoI6PNuzpJy83NXL+u3Wy3h4n4m0EezHAA9TRtZ/68isV1k3kWEL4IDHN/ooWMy8MPVYp5iSgeLOv8iT0hFs3Y0o6NSlFvslV4HzYsBzZM382p4mMEWpoyrbWWvt0K73c9BFoglDnb4ZEtDeg+WMNXCz5p6tcYyjedEjq1zHqF5ilXo6Tul0ft8+/izeJGIly9EZYhye9aiO+O314S62RRaf2HWS4eRLFQzRBR0lpxq88sNuw1Xc4W1Jv2Tkx7WJX29sVwSJXgQIDw7r4rkORHxjmF9zlBxzZ9YK0GW9fLWNdIz2LcBCp9PkALjiF09jvncd5e5VWmHeY34P+2tHzVShV/havga2HbbhX4SlNPxc7AkETIggdX5qomQ77r1lRRB048OF4="
      secure: "B4/Gr7rM0uF867XIxP5nj4ePyFveZ4w7bIeNUDqcW69AgU6y75doOpZw8rhU8EMjpiccs4QKMpGPegi3X/8+ubXZ5jQzizY7cUtsOy7RSIUqrhhl6Yj3vQcaKsC7MXphunxiHq202hvA47/I3IbI0MsCHBeAHrHI8NU/J4KGGELClnyLeTHmiPIT8bAsSpsAqPkviybh8xInixDpUtuXEBkYlemGL5Tk/dzfHd0HTN8F4ITI+WvhpQuv98RmS95LJFc/nT5BVuZXaNiraPgR64ygx5BS2MZ/pCt6FS7V/kmof6/M63OjQMkPNyacM8D5Asb6w7ysFt2NsGB28miL6DOzABhWA4aYVHLtnQI69JL7rKAVm2bl/3wQv7bXRYoRpd/EywShlSX84LwwRVrw3bYfx4/71atO3DzNQhPDwc/4Lb2J0QeHcWwo6+eMbC7BkKGJYBB3Hq1zyEHgbmFHdRcl3IKAX4v9LzXE/bztMCCiDC6w9JavlyHKw4IGAbFRyM+OfJe2r0SX1DoqtDPwxWuhjE3bvBc7FXYAbMItJRgKyXKAxOp7Ntlyz50XzDXbF6161jjLRQMEbNbySt+gkPVy8iTaiEUpErfUzocLqtnYxbzFNS+7W6rJSYvKJY6CHYO29DLrFSPFnMXYbqSEbNSeR+A3qSz9Y/lNCpup3R0="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner